apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-car-park-service
  namespace: kt3-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-car-park-service
  template:
    metadata:
      labels:
        app: cloud-car-park-service
    spec:
      containers:
        - name: cloud-car-park-service
          image: harbor.jianmucloud.com:30003/servicenet/car-park-service:1.0.0
          ports:
            - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-car-park-service
  namespace: kt3-test
spec:
  selector:
    app: cloud-car-park-service
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
