server:
  port: 8087

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.245.1.233:8848
        namespace: prod
  application:
    name: cloud-house-service
  # 配置数据库连接
  datasource:
    username: root
    password: root
    url: jdbc:mysql://10.100.1.223:30006/property_db_cloud?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

knife4j:
  # 开启增强模式，对knife4j的接口测试以及文档编写进行一定个性化设置
  enable: true
  setting:
    language: zh_cn
    enable-open-api: true
  basic:
    enable: false # 是否设置BasicHttp功能 开启则需设置进入Knife4j的账号密码


