---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: apm-agent-pv
  namespace: apm-test
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 10.245.1.233
    path: /data/nfs/agent
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apm-agent-pvc
  namespace: apm-test
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
---
