apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: apm-test
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
    - port: 5601
      nodePort: 32001
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: apm-test
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.14.3
          resources:
            limits:
              memory: "8000Mi"
              cpu: 4000m
            requests:
              memory: "4000Mi"
              cpu: 2000m
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch.apm-test:9200
            - name: ELASTICSEARCH_USERNAME
              value: "kibana_system"
            - name: ELASTICSEARCH_PASSWORD
              value: "changeme"  # replace with your password of kibana_system account in elasticsearch
          ports:
            - containerPort: 5601

