kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-provisioner
spec:
  selector:
    matchLabels:
      app: nfs-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      serviceAccount: nfs-provisioner
      containers:
        - name: nfs-provisioner
          image: us.gcr.io/k8s-artifacts-prod/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nfs-client   # mount the volumes
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: hitices.com/nfs
            - name: NFS_SERVER  # NFS server IP
              value: 10.245.1.233
            - name: NFS_PATH  # the path of shared directory
              value: /data/nfs
      volumes:  # name the nfs shared directory
        - name: nfs-client
          nfs:
            server: 10.245.1.233 # NFS server IP
            path: /data/nfs  # NFS server IP

